//
//  FeedWorker.swift
//  Sprinklr
//
//  Created by B0206635 on 05/12/20.
//  Copyright (c) 2020 B0206635. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NetworkWorker
{
    func fetchProducts(completionHandler: @escaping ([Product]) -> Void) {
        // Dummy data but network call to be implemented.

        completionHandler(fetchDummyProducts())
    }
    
    private func fetchDummyProducts() -> [Product] {
        
        if let filepath = Bundle.main.path(forResource: "model", ofType: "json") {
            do {
                let contents = try String(contentsOfFile: filepath)
                let data = contents.data(using: .utf8)
                
                let products = try JSONDecoder().decode(Feed.FetchProducts.Response.ResponseModel.self, from: data!)
                
                return products.all
            } catch {
                // contents could not be loaded
                return []
            }
        } else {
            print("File not found")
        }
        
        return []
    }
    
    func fetchFilter(completionHandler: @escaping ([String]) -> Void) {
        completionHandler(["All", "EdTech", "Medical", "Machine Learning", "Trending", "Bookmarks"])
    }
}

class PersistantWorker {
    
    func bookmarkProduct(with product: Product) {
        
        var bookmarkedProducts = fetchBookmarkProducts()
        bookmarkedProducts.append(product)
        
        if let encodeObject = try? JSONEncoder().encode(bookmarkedProducts) {
            UserDefaults.standard.set(encodeObject, forKey: "bookmarkedProducts")
        }
    }
    
    func updateBookmarkProduct(with product: Product) {
        do {
            
            guard let encodedProducts = UserDefaults.standard.object(forKey: "bookmarkedProducts") as? Data else {
                return
            }
            
            var products = try JSONDecoder().decode([Product].self, from: encodedProducts)
            
            products = products.map { item in
                if item.id == product.id {
                    return product
                }
                else {
                    return item
                }
            }
            
            if let encodeObject = try? JSONEncoder().encode(products) {
                UserDefaults.standard.set(encodeObject, forKey: "bookmarkedProducts")
            }
            
        }catch { }
        
        return
    }
    
    func removeBookmarkProduct(with id: Int) {
        do {
            
            guard let encodedProducts = UserDefaults.standard.object(forKey: "bookmarkedProducts") as? Data else {
                return
            }
            
            var products = try JSONDecoder().decode([Product].self, from: encodedProducts)
            
            products = products.filter { $0.id != id }
            
            if let encodeObject = try? JSONEncoder().encode(products) {
                UserDefaults.standard.set(encodeObject, forKey: "bookmarkedProducts")
            }
            
        }catch { }
        
        return
    }
    
    func fetchBookmarkProducts() -> [Product] {
        do {
            
            guard let encodedProducts = UserDefaults.standard.object(forKey: "bookmarkedProducts") as? Data else {
                return []
            }
            
            let products = try JSONDecoder().decode([Product].self, from: encodedProducts)
            
            return products
        }catch {
            
        }
        
        return []
    }

}
